language: java
before_install:
- "source ~/virtualenv/python3.6/bin/activate"
install: "pip install -r requirements.txt"
script: 
  - "nohup python3 manage.py runserver &"
  - "cd uitests/"
  - "mvn test"
