language: java
python: 
  - "3.6"
dist: xenial
addons:
  chrome: stable
before_install:
  - "source ~/virtualenv/python3.6/bin/activate"
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
install: "pip3 install -r requirements.txt"
script: 
  - "nohup manage.py runserver &"
  - "cd uitests/"
  - "mvn test"