# Generated by Django 3.0.5 on 2020-04-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='todo',
            new_name='already_read',
        ),
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.CharField(default='admin', max_length=200),
            preserve_default=False,
        ),
    ]
