# Generated by Django 3.0.5 on 2020-05-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20200412_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='completed_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
